site_name: Vector Tactics - Arma 3 Clan
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
# nie ma potrzeby tytułować tutaj, nagłówek # w konkretnym pliku jest jednocześnie tytułem
nav:
  - index.md
  - konfiguracja.md
  - podstawy.md
  - radio.md
  - formacje.md
  - Role:
      - sl.md
      - medic.md
      - sniper.md
      - JTAC-heli.md
  - Dodatkowe: dodatkowe.md

