site_name: Vector Tactics - Arma 3 Clan
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
nav:
  - Strona główna: index.md
  - Manual: manual.md
  - Konfiguracja: konfiguracja.md
  - Radio: radio.md
  - Role:
      - Snajper: sniper.md
      - Medic: medic.md
      - JTAC Heli: JTAC-heli.md
  - Porady: porady-sl.md
  - Optymalizacja: optymalizacja.md
  - Dodatkowe: dodatkowe.md